# Generated by Django 5.1.5 on 2025-01-25 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 25, 22, 39, 19, 977682, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
