# Generated by Django 5.1.5 on 2025-01-26 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_status',
            field=models.CharField(blank=True, choices=[('O', 'Oczekuje'), ('Z', 'Zatwierdzony'), ('R', 'Odrzucony'), ('W', 'W trakcie'), ('X', 'Zakończony')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
