# Generated by Django 5.1.5 on 2025-01-26 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_last_status_vehicle_last_status_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('O', 'Oczekuje'), ('Z', 'Zatwierdzony'), ('R', 'Odrzucony'), ('W', 'W trakcie'), ('X', 'Zakończony')], max_length=1)),
                ('new_status', models.CharField(choices=[('O', 'Oczekuje'), ('Z', 'Zatwierdzony'), ('R', 'Odrzucony'), ('W', 'W trakcie'), ('X', 'Zakończony')], max_length=1)),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicles.vehiclerequest')),
            ],
        ),
    ]
